{
 "title": "Node.js HTTP Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Application Uptime",
   "type": "timeseries",
   "description": "Calculates the total uptime of the application by subtracting the process start time from the current time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM memory used",
   "type": "timeseries",
   "description": "Displays the amount of resident memory (RAM) currently used by the Node.js application process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the rate of CPU time consumed by the application process over time. Useful to monitor CPU-intensive workloads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (4xx/5xx)",
   "type": "gauge",
   "description": "Calculates the rate of client and server errors (HTTP 4xx and 5xx responses). Helps identify issues in the application or user behavior.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"4..|5..\"}[24h])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}